#!/usr/bin/env python3
"""
Install and baseline-configure self-hosted Mengram on Zo Computer.

Usage:
  python3 setup.py install
"""

import argparse
import subprocess
from pathlib import Path
from datetime import datetime

INSTALL_DIR = Path("/home/workspace/mengram-self-hosted")
VENV_HINT = "python3 -m pip install -r requirements.txt"


def run(cmd: str, cwd: Path | None = None, check: bool = True):
    p = subprocess.run(cmd, shell=True, cwd=str(cwd) if cwd else None, capture_output=True, text=True)
    if check and p.returncode != 0:
        raise RuntimeError(f"Command failed: {cmd}\n{p.stderr}")
    return p


def ensure_repo():
    if INSTALL_DIR.exists():
        return
    run(f"git clone https://github.com/alibaizhanov/mengram.git {INSTALL_DIR}")


def ensure_config():
    cfg = INSTALL_DIR / "config.yaml"
    if cfg.exists():
        return
    cfg.write_text(
        """
# Generated by zo-mengram-setup
vault_path: "/home/workspace/mengram-self-hosted/vault"

llm:
  provider: "ollama"
  ollama:
    base_url: "http://localhost:11434"
    model: "llama3.2"

semantic_search:
  enabled: true

security:
  enabled: true
  # Auth is managed through environment variables:
  # MENGRAM_API_KEY
  # MENGRAM_ALLOW_LOCALHOST=false

# Gate defaults
query_gate:
  enabled: true
  gate_mode: "hybrid"
  fallback_behavior: "query"
""".strip()
    )


def ensure_dirs():
    (INSTALL_DIR / "vault").mkdir(parents=True, exist_ok=True)


def install_deps():
    run(VENV_HINT, cwd=INSTALL_DIR)
    run("python3 -m pip install fastapi uvicorn sentence-transformers pyyaml", cwd=INSTALL_DIR)


def print_next_steps():
    print("\nSetup complete.")
    print(f"Install dir: {INSTALL_DIR}")
    print("\nNext steps:")
    print("1) Start Ollama and pull model:")
    print("   ollama serve &")
    print("   ollama pull llama3.2")
    print("2) Set secrets in Zo (Settings > Advanced > Secrets):")
    print("   MENGRAM_API_KEY=<generated-key>")
    print("   MENGRAM_ALLOW_LOCALHOST=false")
    print("3) Start API:")
    print("   cd /home/workspace/mengram-self-hosted && python3 -m api.rest_server_secure config.yaml")
    print("4) Verify:")
    print("   curl -s http://localhost:8420/api/health")
    print("   curl -s http://localhost:8420/api/profile  # should be unauthorized")
    print("\nGenerated at:", datetime.now().isoformat())


def main():
    parser = argparse.ArgumentParser(description="Mengram setup for Zo")
    sub = parser.add_subparsers(dest="command")
    sub.add_parser("install", help="Install Mengram and baseline config")
    args = parser.parse_args()
    if args.command != "install":
        parser.print_help()
        return

    ensure_repo()
    ensure_dirs()
    ensure_config()
    install_deps()
    print_next_steps()


if __name__ == "__main__":
    main()
